<a href="https://colab.research.google.com/github/denverkim/ALGORITHM/blob/main/LAB3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 판다스

In [32]:
# 씨리즈
import pandas as pd

s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])
s

# 데이터 프레임
data = {
'Country': ['Belgium', 'India', 'Brazil'],
'Capital': ['Brussels', 'New Delhi', 'Brasilia'],
'Population': [11190846, 1303171035, 207847528]}
df = pd.DataFrame(data)
print(df.Country[0])
print(df.Capital)
print(df.Population.mean())

data = [['Jan',58,42,74,22,2.95],
        ['Feb',61,45,78,26,3.02],
        ['Mar',65,48,84,25,2.34],
        ['Apr',67,50,92,28,1.02]]

print(data)
df = pd.DataFrame(data, columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])
df

Belgium
0     Brussels
1    New Delhi
2     Brasilia
Name: Capital, dtype: object
507403136.3333333
[['Jan', 58, 42, 74, 22, 2.95], ['Feb', 61, 45, 78, 26, 3.02], ['Mar', 65, 48, 84, 25, 2.34], ['Apr', 67, 50, 92, 28, 1.02]]

  month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58       42           74          22               2.95
1   Feb        61       45           78          26               3.02
2   Mar        65       48           84          25               2.34
3   Apr        67       50           92          28               1.02

In [4]:
pip install construct

Collecting construct
  Downloading construct-2.10.70-py3-none-any.whl.metadata (4.2 kB)
Downloading construct-2.10.70-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 2.5 MB/s eta 0:00:00
Installing collected packages: construct
Successfully installed construct-2.10.70

In [6]:
import construct

In [42]:
# Create a data frame with your class information (courseID, courseName, creditHours, Days) and save it as an Excel file. 이번학기에 듣는 클래스의 정보를 이용하여 데이터프레임을 만든후 엑셀파일로 저장하시요
course = {'courseID': [1111, 2222, 3333],
          'courseName': ['data mining', 'algorithm', 'web crawling'],
          'creditHours': [3, 3, 4],
          'Days': ['Mon', 'Tues', 'Fri']}
course_df = pd.DataFrame(course)
course_df.to_excel('course.xlsx')


# 파일 열기
weather = pd.read_csv('/content/weather.txt')
print(weather.head(3)) #상위 3개
weather.tail() #하위 5개

  month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58       42           74          22               2.95
1   Feb        61       45           78          26               3.02
2   Mar        65       48           84          25               2.34

   month  avg_high  avg_low  record_high  record_low  avg_precipitation
7    Aug        77       59          102          43               0.03
8    Sep        77       57          103          40               0.17
9    Oct        73       54           96          34               0.81
10   Nov        64       48           84          30               1.70
11   Dec        58       42           73          21               2.56