<a href="https://colab.research.google.com/github/denverkim/ALGORITHM/blob/main/LAB4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Read weather.txt file into a dataframe.

import pandas as pd

weather = pd.read_csv('/content/weather.txt')
weather

   month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58       42           74          22               2.95
1    Feb        61       45           78          26               3.02
2    Mar        65       48           84          25               2.34
3    Apr        67       50           92          28               1.02
4    May        71       53           98          35               0.48
5    Jun        75       56          107          41               0.11
6    Jul        77       58          105          44               0.00
7    Aug        77       59          102          43               0.03
8    Sep        77       57          103          40               0.17
9    Oct        73       54           96          34               0.81
10   Nov        64       48           84          30               1.70
11   Dec        58       42           73          21               2.56

In [22]:
# Print first 5 or last 3 rows of df 처음 다섯줄, 마지막 세줄 출력
print('상위 5개 데이터 출력')
print(weather.head())

print('\n하위 3개 데이터 출력')
print(weather.tail(3))

# Get data types, index, columns, values 데이터타입, 인덱스, 컬럼들, 값들
print('\n컬럼별 데이터 타입')
print(weather.dtypes)

# Statistical summary of each column 각 컬럼에 대한 통계요약
print('\n기초 통계량')
print(weather.describe())

# Sort records by any column (descending order)
# 한 컬럼을 정해 내림차순으로 정렬
weather.sort_values('avg_precipitation', ascending=False)

상위 5개 데이터 출력
  month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58       42           74          22               2.95
1   Feb        61       45           78          26               3.02
2   Mar        65       48           84          25               2.34
3   Apr        67       50           92          28               1.02
4   May        71       53           98          35               0.48

하위 3개 데이터 출력
   month  avg_high  avg_low  record_high  record_low  avg_precipitation
9    Oct        73       54           96          34               0.81
10   Nov        64       48           84          30               1.70
11   Dec        58       42           73          21               2.56

컬럼별 데이터 타입
month                 object
avg_high               int64
avg_low                int64
record_high            int64
record_low             int64
avg_precipitation    float64
dtype: object

기초 통계량
        avg_high    avg_low  record_high  record_low  avg_precipitation
count  12.000000  12.000000    12.000000   12.000000          12.000000
mean   68.583333  51.000000    91.333333   32.416667           1.265833
std     7.366488   6.060303    12.323911    8.240238           1.186396
min    58.000000  42.000000    73.000000   21.000000           0.000000
25%    63.250000  47.250000    82.500000   25.750000           0.155000
50%    69.000000  51.500000    94.000000   32.000000           0.915000
75%    75.500000  56.250000   102.250000   40.250000           2.395000
max    77.000000  59.000000   107.000000   44.000000           3.020000

   month  avg_high  avg_low  record_high  record_low  avg_precipitation
1    Feb        61       45           78          26               3.02
0    Jan        58       42           74          22               2.95
11   Dec        58       42           73          21               2.56
2    Mar        65       48           84          25               2.34
10   Nov        64       48           84          30               1.70
3    Apr        67       50           92          28               1.02
9    Oct        73       54           96          34               0.81
4    May        71       53           98          35               0.48
8    Sep        77       57          103          40               0.17
5    Jun        75       56          107          41               0.11
7    Aug        77       59          102          43               0.03
6    Jul        77       58          105          44               0.00

In [40]:
weather1 = weather.drop(['month'], axis=1)
print('\n평균')
print(weather1.mean(axis=1))
print('\n중위수')
print(weather1.median())
print('\n합계')
print(weather1.sum())
print('\n최소값')
print(weather1.min())
print('\n최대값')
print(weather1.max())
print('\n분산')
print(weather1.var())

평균
0     39.790
1     42.604
2     44.868
3     47.604
4     51.496
5     55.822
6     56.800
7     56.206
8     55.434
9     51.562
10    45.540
11    39.312
dtype: float64

중위수
avg_high             69.000
avg_low              51.500
record_high          94.000
record_low           32.000
avg_precipitation     0.915
dtype: float64

합계
avg_high              823.00
avg_low               612.00
record_high          1096.00
record_low            389.00
avg_precipitation      15.19
dtype: float64

최소값
avg_high             58.0
avg_low              42.0
record_high          73.0
record_low           21.0
avg_precipitation     0.0
dtype: float64

최대값
avg_high              77.00
avg_low               59.00
record_high          107.00
record_low            44.00
avg_precipitation      3.02
dtype: float64

분산
avg_high              54.265152
avg_low               36.727273
record_high          151.878788
record_low            67.901515
avg_precipitation      1.407536
dtype: float64

In [48]:
# Slice the records and display the following columns and rows:
# 레코드를 짤라서 다음의 열과 행을 출력
# avg_low
weather.columns
weather.avg_low
weather['avg_low']

# Rows 1 to 2
weather[:2]

# avg_low and avg_high
weather[['avg_low', 'avg_high']]

# 9 row of avg_precipitation column
weather.loc[8, 'avg_precipitation']

# 4 to 5 rows of 1 and 4 columns
weather.iloc[3:5, [0,3]]

  month  record_high
3   Apr           92
4   May           98

In [57]:
# Filter the data and display the following columns and rows:
# 데이터를 검색하여 다음의 열과 행을 출력
# avg_precipitation > 1.0

weather_1 = weather[weather.avg_precipitation > 1.0]

# Month is in either June, July, or August
weather_2 = weather[weather.month.isin(['Jun', 'Jul', 'Aug'])]

In [71]:
# Assign new values in the following locations:
# 101.3 for avg_precipitation column at index 9
weather.loc[9, 'avg_precipitation'] = 101.3
weather

# Np null values for avg_precipitation column at index 9 (np.nan)
import numpy as np

weather.loc[9, 'avg_precipitation'] = np.nan
weather

# 5 for all rows in avg_low column avg_low 컬럼 전체를 5로 바꾸기

weather.avg_low = 5
weather

# Add new column named avg_day that is the average of avg_low and avg_high avg_low와 avg_high의 평균을 구하여 avg_day컬럼을 만듬
weather['avg_day'] = (weather.avg_low + weather.avg_high)/2
weather

,month,avg_high,avg_low,record_high,record_low,avg_precipitation,avg_day
0,Jan,58,5,74,22,2.95,31.5
1,Feb,61,5,78,26,3.02,33.0
2,Mar,65,5,84,25,2.34,35.0
3,Apr,67,5,92,28,1.02,36.0
4,May,71,5,98,35,0.48,38.0
5,Jun,75,5,107,41,0.11,40.0
6,Jul,77,5,105,44,0.00,41.0
7,Aug,77,5,102,43,0.03,41.0
8,Sep,77,5,103,40,0.17,41.0
9,Oct,73,5,96,34,NaN,39.0
10,Nov,64,5,84,30,1.70,34.5
11,Dec,58,5,73,21,2.56,31.5

In [84]:
# Rename columns 컬럼이름 바꾸기
# avg_precipitation to avg_rain
weather.rename(columns={'avg_precipitation': 'avg_rain'}, inplace=True)

# Change columns’ name to 'month','av_hi','av_lo','rec_hi','rec_lo','av_rain‘, ‘av_day’
weather.columns = ['month','av_hi','av_lo','rec_hi','rec_lo','av_rain', 'av_day']

# Save the result data frame to a csv file 데이터플레임을 csv파일로 저장
weather.to_csv('/content/weather.csv')