<a href="https://colab.research.google.com/github/denverkim/ALGORITHM/blob/main/LAB6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [7]:
# 널값이 있는 곳에 TRUE 리턴
data.isna()
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [9]:
# 널값 요약
print(data.isna().sum())

2

In [13]:
# 널값이 아닌 데이터 저장
data1 = data[data.notnull()]
data1

0        1
2    hello
dtype: object

In [33]:
df = pd.DataFrame([[1, np.nan, 2], [2, 3, 5], [np.nan, 4, 6], [np.nan, np.nan, np.nan]])
df.columns = ['c1', 'c2', 'c3']
df.isna().sum()
df.shape
df.mean()
df

    c1   c2   c3
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0
3  NaN  NaN  NaN

In [34]:
# 전체 행이 널값인 경우 제거
df.dropna(how='all')

    c1   c2   c3
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

In [35]:
# 널값이 하나라도 있는 열 제거
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [36]:
df.dropna(how='all')

    c1   c2   c3
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

In [37]:
df.fillna(0)

    c1   c2   c3
0  1.0  0.0  2.0
1  2.0  3.0  5.0
2  0.0  4.0  6.0
3  0.0  0.0  0.0

In [40]:
df.fillna({'c1': 0, 'c2': 99999, 'c3': 111111})

    c1       c2        c3
0  1.0  99999.0       2.0
1  2.0      3.0       5.0
2  0.0      4.0       6.0
3  0.0  99999.0  111111.0